name: Clojure CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ hashFiles('project.clj') != '' }}
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
